version: 2

references:
  defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3-browsers
        environment:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    parallelism: 1
    shell: /bin/bash --login

jobs:
  build_job:
    <<: *defaults

    steps:

    # Machine Setup
    - checkout

    # Restore the dependency cache
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Starting Xvfb (for Browser Tests)
        type: shell
        command: Xvfb :99 -screen 0 1280x1024x24
        background: true

    - run:
        name: Set up path
        command: |
          if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
          export PATH="~/MadKudu/madkudu.js/node_modules/.bin:$PATH"

    - run: npm install

    # Save dependency cache
    - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - ./node_modules

    # Tests

    # This is from Code Climate (see https://docs.codeclimate.com/docs/circle-ci-test-coverage-example#section-circleci-20)
    - run:
        name: Setup test reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          mkdir coverage

    - run: npm test

    - run:
        name: Upload coverage
        command: |
          find ./dist/coverage/unit/Chrome*/lcov.info -exec cp {} ./coverage/ \;
          ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $EXIT_CODE --debug

    - persist_to_workspace:
        root: ~/repo
        paths: .

  publish_job:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - deploy:
          command: npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job:
          context: dev
      - publish_job:
          context: prod
          requires:
            - build_job
          filters:
            branches:
              only: master
