version: 2
jobs:
  build:
    working_directory: ~/MadKudu/madkudu.js
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      CC_TEST_REPORTER_ID: cc4cc3b429117620d21099a292136c912927b6d1feab569c8aa885e1c317a54c
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    # Machine Setup
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run:
        working_directory: ~/MadKudu/madkudu.js
        command: nvm install 6.10.3 && nvm alias default 6.10.3
    # Restore the dependency cache
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    # This is from Code Climate (see https://docs.codeclimate.com/docs/circle-ci-test-coverage-example#section-circleci-20)
    - run:
        name: Setup Code Climate test-reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
    - run:
        name: set up Chrome
        command: |
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb
    - run:
        name: Set up sependencies
        command: |
          if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
          export PATH="~/MadKudu/madkudu.js/node_modules/.bin:$PATH"
          npm install
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules
    # Test
    - run:
        name: Run tests
        command: |
          ./cc-test-reporter before-build
          npm test
          mkdir coverage
          find ./dist/coverage/unit/Chrome*/lcov.info -exec cp {} ./coverage/ \;
          ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $EXIT_CODE
    # Teardown
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
