version: 2

references:
  defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3-browsers

jobs:
  build_job:
    <<: *defaults

    steps:

    # Machine Setup
    - checkout

    # Restore the dependency cache
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}

    - run:
        name: Set up path
        command: |
          if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
          export PATH="~/MadKudu/madkudu.js/node_modules/.bin:$PATH"

    - run: npm install

    # Save dependency cache
    - save_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules

    # Tests

    # - run: npm test

    - persist_to_workspace:
        root: ~/repo
        paths: .

  publish_job:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - deploy:
          command: npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job:
          context: dev
      - publish_job:
          context: prod
          requires:
            - build_job
          filters:
            branches:
              only: master
